server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexMitra/ms-fundamentals-config.git
          search-paths: configurations
          default-label: ms_task_6
          skip-ssl-validation: true
